services:
  ollama:
    build: ./ollama          # 👈 usa nuestro Dockerfile personalizado
    container_name: ollama
    ports:
      - "11500:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    volumes:
      - ./backend:/app
    restart: unless-stopped
frontend:
  build: ./frontend
  ports:
    - "3000:3000"
  depends_on:
    - backend
  environment:
    - VITE_API_URL=http://backend:8000
  volumes:
    - ./frontend:/app
  restart: unless-stopped
volumes:
  ollama_data:



