services:
  ollama:
    build: ./ollama          # 👈 usa nuestro Dockerfile personalizado
    container_name: ollama
    ports:
      - "11500:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5174:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    restart: unless-stopped


  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_seguro
      - MYSQL_DATABASE=mi_base_datos
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password_seguro
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  maria-data:  # Volumen para no perder datos al apagar
  ollama_data:
  mariadb_data:
